steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fashion-clip-search', '.']
  
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fashion-clip-search']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'fashion-clip-search', 
          '--cpu', '8',
          '--memory', '16Gi',
          '--image', 'gcr.io/$PROJECT_ID/fashion-clip-search', 
          '--platform', 'managed', 
          '--region', 'us-central1', 
          '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/fashion-clip-search'

